[build]
  command = "npm run build"
  publish = ".next"

[context.app]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["node_modules/sharp/**/*", ".next/*.json"]
  external_node_modules = ["sharp"]